title: Canadian Social Determinants Urban Laboratory
description: Linking Canadian data to understand health and its social determinants
url: "https://csdul.github.io"
baseurl: ""

markdown: kramdown

exclude:
  - README.md
